import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import qs from "query-string";

import type { paths } from "@/services/paths"; // generated by openapi-typescript

const getBaseUrl = () => {
  if (process.env.NEXT_PUBLIC_VERCEL_BRANCH_URL) {
    return `https://${process.env.NEXT_PUBLIC_VERCEL_BRANCH_URL}`;
  }

  if (process.env.NEXT_PUBLIC_API_URL) {
    return process.env.NEXT_PUBLIC_API_URL;
  }

  return `http://localhost:${process.env.PORT || 3000}`; // Fallback to localhost if no environment variable is set
};

export const fetchClient = createFetchClient<paths>({
  baseUrl: getBaseUrl(),
  querySerializer: (query) =>
    qs.stringify(query, {
      arrayFormat: "bracket-separator",
      arrayFormatSeparator: ",",
      skipNull: true,
      skipEmptyString: true,
    }),
});
export const API = createClient(fetchClient);

export default API;
